# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-15 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puns', '0003_auto_20171025_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='PunWordRu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='PunWord',
            new_name='PunWordEn',
        ),
    ]
